---
{{- if .Values.flow_persistence }}
{{-   if .Values.flow_persistence.mode }}
{{-     if eq .Values.flow_persistence.mode "git" }}
apiVersion: v1
kind: Secret
metadata:
  # secret name has -x suffix to be used as a template
  name: {{ printf "%s--%s" .Release.Name "secrets-git" }}-x
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "nifireg.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  user: {{ .Values.flow_persistence.git.user |default "git-u" |b64enc |quote }}
  pass: {{ .Values.flow_persistence.git.pass |default "git-p" |b64enc |quote }}
{{- end }}
{{- end }}
{{- end }}
