apiVersion: v1
kind: Service
metadata:
  name: {{ include "services.fullname" . }}-headless
  namespace: default
spec:
  clusterIP: None
  # type: NodePort # network type
  selector:
    app: {{ include "services.fullname" . }}
  ports:
  - port: 7777