## helm
repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
  - name: pgbouncer
    chart: ../pgbouncer
    values:
    - users:
        # <username>: <passwd> , get password from db using this query SELECT passwd  FROM pg_shadow WHERE usename = '<username>';
        pgbouncer: setme
      settings:
        auth_type: md5
      databases:
        postgres:
          host: postgresql
          port: 5432
          dbname: postgres
          auth_user: pgbouncer

  - name: postgresql
    chart: bitnami/postgresql
    values:
      - resources:
          requests:
            cpu: "1000m"
            memory: "1Gi"