apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
etcd:
  external:
    endpoints:
    - http://192.168.56.12:2379
    - http://192.168.56.13:2379
    - http://192.168.56.14:2379
kubernetesVersion: "stable"
controlPlaneEndpoint: "192.168.56.18:6443"
apiServer:
  extraArgs:
    apiserver-count: "3"
  certSANs:
  - "192.168.56.18"
  timeoutForControlPlane: 4m0s
certificatesDir: "/etc/kubernetes/pki"
imageRepository: "k8s.gcr.io"
clusterName: "kube-cluster"
