apiVersion: v1
kind: Service
metadata:
  name: {{ include "ps-app.fullname" . }}-service
  namespace: default
spec:
  type: NodePort # network type
  selector:
    app: {{ include "ps-app.fullname" . }}
  ports:
  - port: 9999
    targetPort: 9999
    nodePort: {{.Values.service.nodePort}} # network type