apiVersion: v1
kind: Service
metadata:
  name: {{ include "frontend-app.name" . }}-headless
  namespace: default
spec:
  clusterIP: None
  # type: NodePort # network type
  selector:
    app: {{ include "frontend-app.name" . }}
  ports:
  - port: 4000