FROM confluentinc/cp-kafka-connect:5.5.1

#RUN echo "===> Installing MySQL connector" \
#&& curl https://jdbc.postgresql.org/download/postgresql-42.2.23.jar  --output /usr/share/java/kafka-connect-jdbc/postgresql-42.2.23.jar
RUN echo "===> Installing  NS connector" \
&& curl https://github.com/Athuru-Chaithanya-Kumar/files/blob/main/kafka-connect-jdbc-5.5.1.jar  --output /usr/share/java/kafka-connect-jdbc-5.5.1.jar

