apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
 name: glusterfs
provisioner: kubernetes.io/glusterfs
allowVolumeExpansion: true
parameters:
 resturl: "http://65.108.248.243:8080"
 clusterid: "9c00157cd5f7745ada04cba16e11a529"
 restuser: "admin"
 secretNamespace: "default"
 secretName: "heketi-secret"
 volumetype: "none"
 volumeoptions: "ctime off"
